# Relax Inc 'Take Home Challenge' Solution

In [1]:
from collections import Counter
import numpy as np 
import pandas as pd

### Import and Join Dataframes

In [2]:
user_eng_df = pd.read_csv('takehome_user_engagement.csv')
users_df = pd.read_csv('takehome_users.csv', encoding='latin-1') #would throw error with no encoding

# Full outer join of the 2 tables
data_df = user_eng_df.merge(users_df, left_on='user_id', right_on='object_id', how='outer')

# Remove duplicate/unnecessary columns. 'visited' only has 1 for an entry, trivial column.
del data_df['object_id'], data_df['visited']

### Preprocessing

In [3]:
# If a user is not invited by another user, we give this column a value of 0
data_df.loc[np.isnan(data_df['invited_by_user_id']), 'invited_by_user_id'] = 0

# Drow rows with mostly NaN values
data_df = data_df.dropna()

# Correcting Data Types
data_df['user_id'] = data_df['user_id'].astype(int)
data_df['invited_by_user_id'] = data_df['invited_by_user_id'].astype(int)
data_df['creation_time'] = pd.to_datetime(data_df['creation_time'], format='%Y-%m-%d %H:%M:%S')
data_df['time_stamp'] = pd.to_datetime(data_df['time_stamp'], format='%Y-%m-%d %H:%M:%S')

### 'Adopted User' Label

 - identify  which  factors  predict  future  user adoption .

In [4]:
# Initially set all users as not 'adopted' (0 is false, 1 is true).
data_df['adopted_user'] = 0

# Data of users and how many times each of them have logged in. 
num_logins = data_df['name'].value_counts().values

# Names of users who logged in 3 or more times
valid_users = data_df['name'].value_counts().index[0:len(num_logins[num_logins>=3])]

# Setting a variable to aggregate over
data_df['counter'] = 1
user_labels = []

for idx, user in enumerate(valid_users): 
    user_df = data_df[data_df.name==user]
    # Maximum number of logins in any week for each user
    max_logins = user_df.set_index("time_stamp").resample("7D").sum().dropna()['counter'].max()
    
    if max_logins>=3:
        user_labels.append(1)
    else:
        user_labels.append(0)

# Extracting names of users who are considered 'adopted', and the total num of adopted users
adopted_user_names = valid_users[np.where(np.array(user_labels)==1)]
num_adopted_users = len(adopted_user_names)

# Deleting aggregation counter
del data_df['counter']

# Giving the 'adopted users' their appropriate labels
data_df.loc[data_df['name'].isin(adopted_user_names), 'adopted_user'] = 1

# Do the same for the users dataframe
users_df['adopted_user'] = 0
users_df.loc[users_df['name'].isin(adopted_user_names), 'adopted_user'] = 1

In [5]:
# Deleting a bunch of useless data
del data_df['time_stamp'], data_df['name'], data_df['creation_time']
del data_df['last_session_creation_time']

del users_df['creation_time'], users_df['last_session_creation_time']

### Model Preprocessing

In [6]:
users_df.loc[np.isnan(users_df['invited_by_user_id']), 'invited_by_user_id'] = 0
users_df['invited_by_user_id'] = users_df['invited_by_user_id'].astype(int)

# One hot encode categorical variables
users_df = users_df.join(pd.get_dummies(users_df.creation_source))

# Set the index as the user IDs.
users_df = users_df.set_index(users_df.object_id)

In [9]:
print(users_df)

                          name                                email  \
object_id
1               Clausen August             AugustCClausen@yahoo.com
2                Poole Matthew               MatthewPoole@gustr.com
3            Bottrill Mitchell           MitchellBottrill@gustr.com
4              Clausen Nicklas            NicklasSClausen@yahoo.com
5                    Raw Grace                   GraceRaw@yahoo.com
6                Cunha Eduardo        EduardoPereiraCunha@yahoo.com
7                 Sewell Tyler           TylerSewell@jourrapide.com
8            Hamilton Danielle           DanielleHamilton@yahoo.com
9                   Amsel Paul                PaulAmsel@hotmail.com
10                Santos Carla        CarlaFerreiraSantos@gustr.com
11              Paulsen Malthe             MaltheAPaulsen@gustr.com
12             Mathiesen Lærke            LaerkeLMathiesen@cuvox.de
13               Fry Alexander               AlexanderDFry@cuvox.de
14                 Rivera Bret                BretKRivera@gmail.com
15                 Theiss Ralf               RalfTheiss@hotmail.com
16                  Engel René                ReneEngel@hotmail.com
17            Reynolds Anthony       AnthonyReynolds@jourrapide.com
18            Gregersen Celina      CelinaAGregersen@jourrapide.com
19              Collins Arlene             ArleneRCollins@gmail.com
20               Helms Mikayla                   lqyvjilf@uhzdq.com
21                Hunter Alfie                AlfieHunter@gmail.com
22                Myers Jordan                JordanMyers@gmail.com
23                 Souza Alice           AliceAraujoSouza@gustr.com
24              Woodruff James              JamesTWoodruff@cuvox.de
25                 Stone Elise            EliseStone@jourrapide.com
26              Wexler Florian         FlorianWexler@jourrapide.com
27                 Santos Luís            LuisPintoSantos@gmail.com
28           Weissmuller Marko      MarkoWeissmuller@jourrapide.com
29            Fernandes Evelyn  EvelynSousaFernandes@jourrapide.com
30                  Egger Leah             LeahEgger@jourrapide.com
...                        ...                                  ...
11971        Ferreira Beatrice    BeatriceBarbosaFerreira@yahoo.com
11972          Penington Jamie             JamiePenington@yahoo.com
11973           Simmons Thomas              ThomasSimmons@gmail.com
11974              Scott James                JamesJScott@gmail.com
11975           Daecher Jürgen              JurgenDaecher@gustr.com
11976                Kohl Leah                 LeahKohl@hotmail.com
11977             Crary Joshua               JoshuaHCrary@gmail.com
11978             Castro Pedro           PedroCunhaCastro@gustr.com
11979             Hurst Harley                HarleyHurst@yahoo.com
11980      Gloeckner Franziska                   ljnnbqdr@cgbld.com
11981                Fry Tyler                   TylerFry@gmail.com
11982            Barajas Maria              MariaCBarajas@gmail.com
11983               Engel Mike                  MikeEngel@gmail.com
11984               Reed Cerys                  CerysReed@yahoo.com
11985         Jespersen Marcus            MarcusTJespersen@cuvox.de
11986            Ribeiro Clara         ClaraBarrosRibeiro@gmail.com
11987               Reed Poppy                   ftdkorrj@uyhoy.com
11988              Minick John                JohnFMinick@yahoo.com
11989           Pereira Emilly      EmillyOliveiraPereira@gmail.com
11990                Juhl Aase             AasePJuhl@jourrapide.com
11991            Vaughn Arthur              ArthurJVaughn@gmail.com
11992         Hermansen Amanda           AmandaAHermansen@yahoo.com
11993          Townsend Isabel              IsabelTownsend@cuvox.de
11994           Grimstone Joel                   conxzghp@eaouk.com
11995         Werfel Sebastian            SebastianWerfel@gmail.com
11996             Meier Sophia                SophiaMeier@gustr.com
11997            Fisher Amelie               AmelieFisher@gmail.com
11998              Haynes Jake                  JakeHaynes@cuvox.de
11999             Faber Annett                   mhaerzxp@iuxiw.com
12000               Lima Thaís            ThaisMeloLima@hotmail.com

           opted_in_to_mailing_list  enabled_for_marketing_drip  org_id  \
object_id
1                                 1                           0      11
2                                 0                           0       1
3                                 0                           0      94
4                                 0                           0       1
5                                 0                           0     193
6                                 0                           0     197
7                                 0                           1      37
8                                 1                           1      74
9                                 0                           0     302
10                                1                           1     318
11                                0                           0      69
12                                0                           0     130
13                                0                           0     254
14                                0                           0       0
15                                0                           0     175
16                                0                           0     211
17                                1                           0     175
18                                0                           0       2
19                                1                           0       0
20                                0                           0      58
21                                0                           0      54
22                                0                           0       7
23                                1                           0       6
24                                1                           0     123
25                                1                           0      81
26                                0                           0      56
27                                0                           0     134
28                                0                           0       6
29                                0                           0      92
30                                0                           0     251
...                             ...                         ...     ...
11971                             0                           0       3
11972                             0                           0      16
11973                             0                           0      52
11974                             0                           0     167
11975                             1                           0      31
11976                             0                           0     248
11977                             0                           0     144
11978                             1                           0      29
11979                             0                           0       2
11980                             0                           0     406
11981                             0                           0     110
11982                             1                           1      57
11983                             0                           0     234
11984                             0                           0     170
11985                             0                           0      74
11986                             0                           0     111
11987                             0                           0       1
11988                             0                           0     114
11989                             1                           0      22
11990                             0                           0      25
11991                             0                           0     388
11992                             0                           0     129
11993                             0                           0     281
11994                             0                           0      84
11995                             0                           0       0
11996                             0                           0      89
11997                             0                           0     200
11998                             1                           1      83
11999                             0                           0       6
12000                             0                           1       0

           invited_by_user_id  adopted_user  GUEST_INVITE  ORG_INVITE  \
object_id
1                       10803             0             1           0
2                         316             1             0           1
3                        1525             0             0           1
4                        5151             0             1           0
5                        5240             0             1           0
6                       11241             0             1           0
7                           0             0             0           0
8                           0             0             0           0
9                           0             0             0           0
10                       4143             1             0           1
11                          0             0             0           0
12                       9270             0             0           1
13                      11204             0             0           1
14                          0             0             0           0
15                          0             0             0           0
16                          0             0             0           0
17                       1600             0             1           0
18                       3153             0             1           0
19                          0             0             0           0
20                          0             1             0           0
21                          0             0             0           0
22                       2994             0             0           1
23                         23             0             0           1
24                          0             0             0           0
25                       6312             0             1           0
26                      11857             0             0           1
27                       4189             0             0           1
28                          0             0             0           0
29                          0             0             0           0
30                       4835             0             1           0
...                       ...           ...           ...         ...
11971                   11854             0             1           0
11972                    7012             0             0           1
11973                       0             0             0           0
11974                       0             0             0           0
11975                    6410             1             1           0
11976                       0             0             0           0
11977                       0             0             0           0
11978                       0             0             0           0
11979                       0             0             0           0
11980                    3068             0             0           1
11981                    5775             0             1           0
11982                    2527             0             0           1
11983                       0             0             0           0
11984                       0             0             0           0
11985                       0             0             0           0
11986                       0             0             0           0
11987                       0             0             0           0
11988                       0             1             0           0
11989                       0             0             0           0
11990                    3944             0             0           1
11991                       0             0             0           0
11992                       0             0             0           0
11993                       0             0             0           0
11994                    5450             0             1           0
11995                       0             0             0           0
11996                    8263             0             0           1
11997                       0             0             0           0
11998                    8074             0             1           0
11999                       0             0             0           0
12000                       0             0             0           0

           PERSONAL_PROJECTS  SIGNUP  SIGNUP_GOOGLE_AUTH
object_id
1                          0       0                   0
2                          0       0                   0
3                          0       0                   0
4                          0       0                   0
5                          0       0                   0
6                          0       0                   0
7                          0       1                   0
8                          1       0                   0
9                          1       0                   0
10                         0       0                   0
11                         0       1                   0
12                         0       0                   0
13                         0       0                   0
14                         0       1                   0
15                         1       0                   0
16                         1       0                   0
17                         0       0                   0
18                         0       0                   0
19                         0       1                   0
20                         0       1                   0
21                         1       0                   0
22                         0       0                   0
23                         0       0                   0
24                         0       1                   0
25                         0       0                   0
26                         0       0                   0
27                         0       0                   0
28                         0       1                   0
29                         0       1                   0
30                         0       0                   0
...                      ...     ...                 ...
11971                      0       0                   0
11972                      0       0                   0
11973                      1       0                   0
11974                      0       1                   0
11975                      0       0                   0
11976                      1       0                   0
11977                      0       0                   1
11978                      1       0                   0
11979                      0       1                   0
11980                      0       0                   0
11981                      0       0                   0
11982                      0       0                   0
11983                      0       0                   1
11984                      0       1                   0
11985                      1       0                   0
11986                      0       0                   1
11987                      0       1                   0
11988                      1       0                   0
11989                      0       0                   1
11990                      0       0                   0
11991                      0       0                   1
11992                      1       0                   0
11993                      1       0                   0
11994                      0       0                   0
11995                      1       0                   0
11996                      0       0                   0
11997                      0       0                   1
11998                      0       0                   0
11999                      1       0                   0
12000                      0       1                   0

[12000 rows x 12 columns]

In [8]:
del users_df['creation_source'], users_df['object_id']